name: CI-ML-Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader stopwords punkt wordnet

      - name: Run pipeline
        run: |
          python src/load_data.py
          python src/preprocess.py
          python src/train.py
          python src/evaluate.py

      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: mlruns/
